### PR TITLE
Add Polygons example: show examples of all poly in h3d.prim

### PR DESCRIPTION
**Pull request by neokeld**
In this PR, i add an example of polygons from h3d.prim : 

- Grid
- Cube
- Cylinder
- Disc
- Geosphere
- Sphere

I also try to add arrow key movements but i'm not sure of the implementation.
Feel free to criticize.

### CODE REVIEW

**Comment by ncannasse** [comment]
Don't use addEventTarget but instead override update for keys and add a CameraController (see Base3d).

**Comment by neokeld** [comment]
Thanks a lot ! I've corrected this using overriding as you suggested and this has greatly simplified the implementation.

**Comment by ncannasse** [comment]
No need for castle inspector, it's been deprecated ;)

**Comment by neokeld** [comment]
Thx i've removed it :)

**Pull request merged**
