### PR TITLE
add Circle primitive

### PR DESCRIPTION
**Pull request by tong**
Example: http://tmp.disktree.net/heaps-primitives/  
Use `W` to toggle wireframe.

### CODE REVIEW

**Comment by ncannasse** [comment]
Maybe it should be Disc instead of Circle ?

**Comment by tong** [comment]
Not sure.
As a blender user i would expect Circle, but:

Blender: Circle
Maya: Disc
Threejs: Circle

**Comment by ncannasse** [comment]
I think Disc is more appropriate.

**Comment by ncannasse** [comment]
Thanks!

**Pull request merged**
