### PR TITLE
add Spotlight shader sample

### PR DESCRIPTION
**Pull request by Simn**
The shader code is ported and simplified from https://www.tomdalling.com/blog/modern-opengl/08-even-more-lighting-directional-lights-spotlights-multiple-lights/

I left out some aspects (specular etc.) to focus on how to actually write shaders.

### CODE REVIEW

**Comment by ncannasse** [comment]
I don't think it should be necessary to calculate the acos of the angle, one method only involving vector dot product should be feasible.

**Comment by ncannasse** [comment]
Also, lightConeDirection should be normalized before being passed to the shader, so you don't have to renormalize for every pixel

**Comment by Simn** [comment]
I'll fix the acos one.

For the direction, I think at the very least I have to clone the vector because having x/y/z sliders and normalizing doesn't mix that well.

**Comment by Simn** [comment]
Changed both, please check.

My documentation is off now because the comparison operator flipped (`lightToSurfaceAngle < lightConeAngle`). Have to understand why exactly before I update the documentation...

**Comment by ncannasse** [comment]
Another optimization :  pow( length(surfaceToLight) , 2.0)  is actually surfaceToLight.dot(surfaceToLight)

**Comment by Simn** [comment]
Whoops, I meant to get rid of that clone entirely. But yes, loading into the shader variable makes even more sense.

**Comment by ncannasse** [comment]
Regarding your change : I don't have previous code but `a.dot(b) == a.length() * b.length() * cos(a,b)`

**Comment by Simn** [comment]
Updated the direction and the pow. Still have to check the cos.

**Comment by ncannasse** [comment]
Closing for now, please resubmit not as a sample but as separate files (h3d/SpotLight.hx , h3d/shader/SpotLight.hx + sample).

**Pull request closed without merging**
