### PR TITLE
Display line number next to properties on domkit inspector

### PR DESCRIPTION
**Pull request by Speedphoenix**
This depends on this domkit PR:
https://github.com/HeapsIO/domkit/pull/55

image

### CODE REVIEW

**Comment by Speedphoenix** [comment]
Last commit allows reading .map to display source transpiled files
image

**Comment by Speedphoenix** [comment]
The question remains as to whether we want to keep the full path with folders or only the filename

**Comment by ncannasse** [comment]
Where is located the SourceMap file and why it's not enabled by default ? :)

**Comment by ncannasse** [comment]
Usually we keep a relative path to either the project root or the "/res"
file, so it can easily be turned into a full path

**Comment by Speedphoenix** [comment]
For less, source maps are located in the same place as the generated style by default (style.css will have style.css.map in the same repository)   
To generate it:
- With the EasyLess vscode extension, in settings.json: `"less.compile": { "sourceMap": true, }`
- With the lessc command: `--source-map`

For the source map path I already used hxd.res.Loader.currentInstance so that it would be relative to "/res". My comment was about displaying only the file name for less sources in the inspector, since, at least on DSW, they are all always in the same folder
image

**Pull request merged**
