### PR TITLE
Added hxd.res.Config.ignoredDirs

### PR DESCRIPTION
**Pull request by deepnight**
Added a Map to res Config to ignore a specific set of directories (eg. backups or other cache related things)

### CODE REVIEW

**Comment by ncannasse** [comment]
I think these should be configured as part of `res/props.json` which are already used for hide and convert configuration. 

```json
{
  "fs.convert" : {
      ...
  },
  "fs.exclude" : ["backups", "path/to/file.png"]
}
```

**Comment by deepnight** [comment]
Well, to me it feels like that there's some obscure redundancies/overlaps between Config and the JSON then. Not sure which one is actually better here 🤔

**Comment by Yanrishatum** [comment]
props.json have two major issues:
1. You can't append custom configurations from libraries (for example - add converts)
2. It's extremely undocumented and obscure.

On other hand Config can be edited by external libraries, as it's macro-time.
I think for props.json to become more usable there should be a proper documentation on how it's used as well as support for props chaining, allowing for libraries to append their own configurations. (In which case usage of ldtk library could just add `backups` into FS exclude list in its own props.json)
Heaps in general have a weird disconnect that some things have to be added via props.json, but others can be done only via macro (which also poorly documented) and vice-versa.

**Comment by ncannasse** [comment]
I can merge the commit but without any default directory ignored ;)

**Comment by deepnight** [comment]
Thanks, sounds good! Should I make another PR?

**Comment by ncannasse** [comment]
You can update this one

Le ven. 1 avr. 2022 à 12:04, Sébastien Bénard ***@***.***> a
écrit :

**Comment by deepnight** [comment]
Done! :)

**Pull request merged**
