### PR TITLE
Fixup for Haxe4.2+

### PR DESCRIPTION
**Pull request by Yanrishatum**
* Rename `Api.is` to `Api.isOfType` - fixes `is` warning.
* Fix travis for haxe-dev on DebugMode.Full. I have to note that this is a regression compared to 4.1 and it should resolve it as DebugMode abstract, but for whatever reason it doesn't.

Note: Wait for travis checks to complete before merge in case it will fail at something else.

### CODE REVIEW

**Comment by ncannasse** [comment]
I think DebugMode.Full has been fixed on haxe dev, can you revert this change ?

**Comment by Yanrishatum** [comment]
Can't confirm if it's fixed or not, because now it fails at completely different point:
```
/home/travis/build/HeapsIO/heaps/hxsl/Printer.hx:235: characters 16-18 : Unmatched patterns: OpSpread
/home/travis/build/HeapsIO/heaps/hxsl/Printer.hx:235: characters 16-18 : ... For function argument 'v'
/home/travis/build/HeapsIO/heaps/hxsl/DynamicShader.hx:20: character 1 : Build failure
```

**Comment by Yanrishatum** [comment]
No, it's still not fixed: https://travis-ci.org/github/HeapsIO/heaps/jobs/750532653#L522

**Comment by ncannasse** [comment]
Yeah I mistake "Issue closed" with "Fixed" :D I have push a fix, let's see...

**Comment by Yanrishatum** [comment]
Bump. 👀

**Comment by qkdreyer** [comment]
I'm still having this issue

```
/usr/local/lib/haxe/lib/heaps/1,8,0/hxsl/Printer.hx:234: characters 16-18 : Unmatched patterns: OpSpread
/usr/local/lib/haxe/lib/heaps/1,8,0/hxsl/Printer.hx:234: characters 16-18 : ... For function argument 'v'
/usr/local/lib/haxe/lib/heaps/1,8,0/h3d/pass/Default.hx:3: characters 1-8 : Build failure
```

```
$ haxe --version
4.2.0
```

```
$ haxelib list
castle: [1.6.1]
deepnightLibs: [1.0.59]
format: [3.5.0]
hashlink: [0.1.0]
heaps: [1.8.0]
hlopenal: [1.5.0]
hlsdl: [1.10.0]
hxbit: [1.5.0]
ldtk-haxe-api: [0.7.2-rc.1]
 ```

**Comment by qkdreyer** [comment]
Nevermind, I fixed it using `haxelib dev heaps /path/to/heaps`

**Pull request merged**
