### PR TITLE
add option to enable buffering for emitTile

### PR DESCRIPTION
**Pull request by ZwodahS**
Add option "heaps_buffering" to enable buffering in emitTile.

### CODE REVIEW

**Comment by ncannasse** [comment]
This is a quite old option that hasn't been tested in years. Does it still works ? :D

**Comment by Yanrishatum** [comment]
It does, and from what I know from implementation - should work fairly reliably, since `beginDraw` does thorough checks and flushes if there's any deviations like shader composition change, texture swap or filter shenanigans. And I don't see any obvious fault positions from what I know (there may be edge cases, but should work fine for most cases).

However I don't like the naming of the switch, as it's not very intuitive what kind of buffering it enables. While it's longer, but I'd rename it to `heaps_emit_tile_buffering` or something like that. 
In general, I see no problem giving ability to enable it with a compilation flag. Since it's gated behind compilation flag - it's basically "use at your own risk", same with enabling MP3 in Res completion and such.

**Comment by ncannasse** [comment]
Agreed that heaps_buffering is too "generic"

**Comment by ZwodahS** [comment]
I've been testing this for the last 2-3 weeks, doesn't seem to have problem. Was just curious why there wasn't a flag for this. 

Will change the flag and rebase onto the new master.

**Comment by ZwodahS** [comment]
Additional context as to why I investigated this.

I needed some form of layer in SpriteBatch like h2d.Layers, and was going to implement it but found that I could just use Bitmaps and Layers with this flag turn on.

**Pull request merged**
