### PR TITLE
Fixed JS version of hxd.File.browse on Chrome

### PR DESCRIPTION
**Pull request by deepnight**
For some obscure reason, the method used to upload a file to an app on Chrome didn't work sometimes (the Open window would pop-up, but the onChange callback wasn't called).

The new version adds the <input> element to the actual <body> and it stays there, hidden.

### CODE REVIEW

**Comment by ncannasse** [comment]
Could we have instead a modified version that removes it once the callback is triggered ? I think that keeping an element in the tree this way was causing some other problems. Maybe also try by simply keeping the element in a static Array (for Garbage Collector) and removing before callback triggered.

**Comment by deepnight** [comment]
I removed the input when callback is called. It seems to work fine, but it needs a little bit more public testing. I will see if I don't get any report on my app for the next few days.

**Comment by deepnight** [comment]
It's working so far for me. It could be merged, if you're ok too :)

**Comment by ncannasse** [comment]
Thanks!

**Pull request merged**
