### PR TITLE
Add NodeJS support

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by ncannasse** [comment]
We don't want a null driver for nodejs as we are using the library for NWJS which uses JS backend + NodeJS API ;)

**Comment by qkdreyer** [comment]
I’m not sure to understand what you’re implying here. My goal was to run a heaps game server using Node.js on an Unix OS.

**Comment by ncannasse** [comment]
Your current implementation assumes that when having -lib hxnodejs (which
defines nodejs as well i think) the app will run in commandline with no
browser webgl output, which is not the case when compiling for Nwjs which
allows both HTML5 and nodejs API.

Le dim. 28 févr. 2021 à 14:33, Quentin Dreyer <notifications@github.com> a
écrit :

**Comment by qkdreyer** [comment]
Hmm I see. What do you think about checking document != null instead ?

**Comment by qkdreyer** [comment]
@ncannasse Can you have a look at this PR again please ?

**Comment by ncannasse** [comment]
Please fix CI errors first please :) -- apart from Vulkan one (my side)

**Comment by qkdreyer** [comment]
@ncannasse should be good now

**Comment by ncannasse** [comment]
This is not correct... you are setting NullDriver on HLSDL, and break gamepad support in not js platforms as well...

**Comment by qkdreyer** [comment]
Is it better now ?

**Comment by ncannasse** [comment]
Good for me, thanks !

**Pull request merged**
