### PR TITLE
Adding support for Hiero .fnt format

### PR DESCRIPTION
**Pull request by starburst997**
Support for [Hiero](https://libgdx.badlogicgames.com/nightlies/runnables/runnable-hiero.jar) from [libGDX](https://github.com/libgdx/libgdx)

### CODE REVIEW

**Comment by ncannasse** [comment]
How complete/stable it is ? (before merging)

**Comment by ncannasse** [comment]
Referencing #445 as it's related.

**Comment by Yanrishatum** [comment]
Looks like we both implemented same format support. Implementation details slightly differ, but this one have multiple issues:
* Does not account for format containing multiple spaces between records.
* Does not account for string field containing spaces while being enclosed in `"..."` (e.g. `face="El Messiri"` would be parsed as `"El` by this version)
* Does not parse `baseLine`
* Does not parse kerning pairs
* Parses `xadvance`, but for some reason uses `width - 1` in place where it should be used.
* For some reason ignores space character.

**Comment by starburst997** [comment]
Oh yeah, it was a basic implementation worked for my use case but not complete

**Pull request closed without merging**
