### PR TITLE
Improve BitmapFont processing

### PR DESCRIPTION
**Pull request by Yanrishatum**
This PR gives some love to the font support. As littera was working with [BMF format](http://www.angelcode.com/products/bmfont/), I figured introducing more extensive support of it.

* Added support for binary and text BMF.
* Fixed parsing of XML to not rely on generator faithfullness to specs. While Littera does not generate `<?xml ...` header, BMFont does, hence the change. New detection checks if `<font>` node contains `<info>` node which present only in BMF, but not in Divo.
* Littera XML: Parse baseLine. Divo does not provide `baseLine`, but is present in BMF. As a result, `baseLine` guessing required only for Divo. 
* Text sample: Showcase of format support.

Not sure, but I think #367 refers to baseline calculation being imprecise. Due to this changes, all supported formats except Divo should have this issue resolved.

Additional notes: BMF also have support for multiple texture atlases (pages). I did not made support to it, but ideally it should be able to support it. (And it would simplify the text sample, because it would use less PNG images ;) )

UPD: Closes #386 as more comprehensive implementation.

### CODE REVIEW

**Comment by ncannasse** [comment]
While you're at it, you might want to look at #352 : the idea would be to treat fonts descriptors the way we treat fbx files, by preprocessing them and creating a single fast-to-load binary file. Tell me if instead you just want me to merge this PR.

**Comment by Yanrishatum** [comment]
Implemented BFNT writer. It uses different structure, orienting on fast parsing directly into `h2d.Font`. But due to this, I had to replicate variables and some functions `h2d.Font`, `h2d.Font.FontChar`, `h2d.Font.Kerning` and `h2d.Tile` due to Convert being called in macro context, and type parsing of `h2d.Font` leads to resolving of `@:build` in `h3d.mat.Pass` which is disallowed in macro context.

**Comment by ncannasse** [comment]
f158249374808c7e1c6c403aab32a98745ec6bae should help with classes redefinitions : you should now be able to use h2d.Font from within macros

**Comment by ncannasse** [comment]
Good for merge. Now next logical step would be to contribute the corresponding documentation here:
https://github.com/HeapsIO/heaps-doc/blob/master/Text.md

**Pull request merged**
