### PR TITLE
Fix cancelEvents and propagateEvents.

### PR DESCRIPTION
**Pull request by rainyt**
propagate default is true, It can never become false

### CODE REVIEW

**Comment by rainyt** [comment]
My test environment is Mac, and the default value of propagate returned by MAC is true. Propagateevents = false will never take effect.

**Comment by ncannasse** [comment]
ping @trethaller

**Comment by trethaller** [comment]
@rainyt I don't understand, by default [hxd.Event.propagate](https://github.com/HeapsIO/heaps/blob/master/hxd/Event.hx#L31) is false. What do you mean by "default value of propagate returned by MAC"?

**Comment by rainyt** [comment]
Sorry, I don't know why. It's normal now. The previous default value returned is t

**Pull request closed without merging**
