### PR TITLE
fix: handle normalized SDL touch coordinates

### PR DESCRIPTION
**Pull request by qkdreyer**
https://wiki.libsdl.org/SDL_TouchFingerEvent

N.B. : Since we're rounding the normalized value using 100 factor, we can have an 1% windowWidth pixel loss (`792px` vs `799px` for `800px` default windowWidth), maybe we should increase the factor by 10 there and here, what do you think @ncannasse ?

https://github.com/HaxeFoundation/hashlink/blob/a30209ef5020fce4b3b1cda3e7a4fed2edd7f118/libs/sdl/sdl.c#L186-L203

### CODE REVIEW

**Comment by ncannasse** [comment]
I agree it should be scaled up by 100 , from *100 to *10000

**Comment by qkdreyer** [comment]
https://github.com/HaxeFoundation/hashlink/pull/379

**Comment by ncannasse** [comment]
Could you do  `static inline var TOUCH_SCALE = #if (hl_ver >= version("1.12.0")) 10000 #else 100 #end`
Would require compiling with -D hl-ver=1.12.0 , but at least that doesn't break current HL.

**Comment by ncannasse** [comment]
#if hsdl around it please ? :D

**Comment by qkdreyer** [comment]
Done ;)

**Comment by ncannasse** [comment]
Thanks!

**Pull request merged**
