### PR TITLE
Add mat3 from floats and TMat3 | TMat4 * Vec

### PR DESCRIPTION
**Pull request by 0xA3**
Allow Mat3 initialization with floats
Allow Mat3 * Vec3 and Mat4 * Vec4
See: [Issue #811](https://github.com/HeapsIO/heaps/issues/811)

### CODE REVIEW

**Comment by ncannasse** [comment]
I don't want to allow   mat x vec  because that does not work the way the user intended. matrixes are stored column-major so you want to do  vec x  mat = vec3( vec.x * Mat[0] , vec.y * Mat[1], vec.z * Mat[2])  , while mat x vec = vec3( vec3(Mat[0].x,Mat[1].x,Mat[2].x) * vec.x, ..... )

Has this constructor with 9 floats been tested with both GL and DX ?

**Comment by 0xA3** [comment]
Thanks. I removed Mat x Vec
I testet the constructor with 9 floats with GL, DX and AGAL. I created some test projects if you want to check:
[test AGAL](https://github.com/0xA3/test_hxsl/blob/master/yuv_color_agal/src/Main.hx)
[test GLSL](https://github.com/0xA3/test_hxsl/blob/master/yuv_color_glsl/src/Main.hx)
[test HLSL](https://github.com/0xA3/test_hxsl/blob/master/yuv_color_hlsl/src/Main.hx)

**Comment by ncannasse** [comment]
Please resolve conflict and fix tab ;)

**Comment by 0xA3** [comment]
The conflicts are resolved and I verified it with the test projects.

**Pull request merged**
