### PR TITLE
s2d camera bugfix and zoom added

### PR DESCRIPTION
**Pull request by AxGord**

### CODE REVIEW

**Comment by ncannasse** [comment]
@Yanrishatum any insight?

**Comment by Yanrishatum** [comment]
No objections. My 2d camera rework isn't going to be done anytime soon due to workload. So, having bad camera slightly less bad is a good thing.

**Comment by JarduDray** [comment]
So why return scaleX for zoom? Wouldn't getting the value of viewWidth/viewHeight (to get the aspect ratio) multiplied by scaleX be a better option so that everything stays proportional to the screen size, especially when running different resolutions and monitor types?

**Comment by AxGord** [comment]
@JarduDray It is assumed that scaleX == scaleY is always.

**Comment by ncannasse** [comment]
Please reopen the PR, some other PR related to Camera was merged in between.

**Pull request closed without merging**
