### PR TITLE
Enable high shader precision in WebGL

### PR DESCRIPTION
**Pull request by lbergman**
Shaders are currently compiled using mediump which is fine in many cases, but will result in precision issues on many devices. For example shadows becomes very strange if not using highp, and issues like #602 is probably related.

I added MAX_PRECISION constant to GlDriver so that one can choose if highp should enabled or not. I set it to mediump by default to ensure that behavior is same as before. I think highp would be a sensible default but don't want to risk causing issues for existing projects.

So to enable high precision, somewhere before compiling shaders one has to do `GlDriver.MAX_PRECISION = 'highp';`to enable.

And to check highp support, for example to see if it is a good idea to enable shadows:
``` 
public function hasHighPrecision() {
	final driver:h3d.impl.GlDriver = cast h3d.Engine.getCurrent().driver;
	return driver.getMaxPrecision() == 'highp';
}
```

### CODE REVIEW

**Comment by ncannasse** [comment]
The PR is fine, however I'm curious whereas we should allow such high level global change from mediump to highp instead for instance allowing @highp as variable qualifier - that would only be enabled if the devices supports it ofc.

What's your take on this?

**Comment by lbergman** [comment]
Do you mean that it should be possible to set per shader?

Agreed, I was thinking the same, but figured it was a bit more complicated change, and that regardless it makes sense to be also be able to have a default max precision if supported.

For our games I didn't notice any obvious performance issue with switching to highp, and for example three.js uses 'highp' per default as well. But I will do more testing on more devices and if we find it necessary to control precision per shader I will make another MR.

**Comment by ncannasse** [comment]
I meant more per-variable.
But if several popular libraries are using highp by default when supported
I think we should do the same. So please update your PR with "highp" as the
default max precision.
Also, we might want set highp for GL desktop as well?

**Comment by lbergman** [comment]
Yes, it would be nice to expose variable precision as well. 
I got a report about degraded performance on one machine in a build including this change. Could be something else, but I like to investigate to see if we need more finegrained control over precision right now, in which case I will look in to adding that.

But perhaps a separate PR in that case? Should I just modify this to use highp default and apply to all gl targets for now?

**Comment by ncannasse** [comment]
> I got a report about degraded performance on one machine in a build including this change.

Let's wait for more feedback on this first

**Comment by lbergman** [comment]
Finally got feedback from the the machine that started dropping frames, and it seems like when  reverting to mediump performance was back to normal.

Now this is a somewhat problematic machine that often shows worse performance than other machines we test with, so our conclusion is that highp is still a sensible default for shaders, but that we would like to be able to have control per shader and variable.

Very busy with some releases right now, but will have a look at if I can get a PR together as soon as I get a chance.

**Comment by zommerfelds** [comment]
Hi!

I'm running into issues drawing shapes (h2d.Graphics) and sprites with pretty simple scenes. Positions are off and shapes distorted.

Similar description to this issue in different engine: https://forum.defold.com/t/terrible-distortions-just-2-screens-away-from-origin-android-def-3946/52325

It sounds like setting `highp` would fix the issue. Is there a plan to support this with a global option?

**Comment by lbergman** [comment]
Now defaulting to highp for vertex shaders since #960, and this is no longer needed.

**Pull request closed without merging**
