### PR TITLE
Updated h2d.col.Line with angle() and length() methods

### PR DESCRIPTION
**Pull request by Syopic**
Line.angle()  - The angle between a line and the x-axis
Line.length()  - Distance between line points

### CODE REVIEW

**Comment by ncannasse** [comment]
I prefer if we don't store dx/dy, because the points can be mutated, and also because it consumes more memory if you have many lines only to save a few fast subtract.

**Comment by Syopic** [comment]
Yes, really. I will delete the cache. 
Are these methods necessary at all? I was surprised that there was no method for calculating the absolute length of the line. By analogy I can add these methods to h2d.col.Segment.

**Comment by ncannasse** [comment]
Yes I think they can be added, we have not yet designed the whole col API with all methods, only the ones we need when we need them. Please also avoid reformatting existing code in the PR.

**Comment by ncannasse** [comment]
typo to `length`

**Comment by ncannasse** [comment]
Also use hxd.Math.distance

**Comment by Syopic** [comment]
More writings than benefitі of this pool request, but thank you)

**Pull request merged**
